### ISSUE TITLE
windows error, operation not permitted

### ISSUE THREAD

**Issue by si458** [svdgraaf/serverless-basic-authentication#9] opened 2019-05-25 16:47 UTC
Hi
it doesnt seem to work on windows for some reason, i just keep getting a error
``EPERM: operation not permitted, symlink 'C:\Users\User\Documents\myapi\node_modules\serverless-basic-authentication/basic_auth.py' -> 'C:\Users\User\Documents\myapi/basic_auth.py'``
any ideas?

**Comment by svdgraaf** [comment] 2019-05-27 06:24
AFAIK this plugin is incompatible with Windows as of today. It symlinks the file to your local project, and removes it later. afaik, symlinking doesn't work on Windows?

I haven't used Windows in quite a while, so I could be mistaking.

**Comment by si458** [comment] 2019-05-28 11:01
i believe #10 should fix the issue as it seems to be working on mine without any issues :)

**Comment by illagrenan** [comment] 2019-07-09 14:47
I can confirm the same error on my machine:

```powershell
PS C:\> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      18362  0
```

This PR also works for me: https://github.com/svdgraaf/serverless-basic-authentication/pull/10

I had to install this plugin directly from GitHub:

```bash
 npm install svdgraaf/serverless-basic-authentication#develop
```

**Comment by svdgraaf** [comment] 2019-07-09 15:30
Oh crap, I see I didn't actually publish a new version, on it!

**Comment by svdgraaf** [comment] 2019-07-09 15:36
I just release `0.14.0`, can you verify that everything works as expected on Windows? :) 

Thanks a bunch!

**Comment by illagrenan** [comment] 2019-07-09 20:42
> 
> 
> I just release `0.14.0`, can you verify that everything works as expected on Windows? :)
> 
> Thanks a bunch!

The latest version works like a charm, I just tested it. Thanks for a great job! ✨🚀👍😄

**Comment by svdgraaf** [comment] 2019-07-10 07:32
Perfect, I'll close this issue

**Closed as completed by svdgraaf** 2019-07-10 07:32 UTC
Labels: enhancement, help wanted
